name: Actualizar horarios cada minuto

on:
  schedule:
    - cron: "*/1 * * * *"  # cada minuto
  workflow_dispatch:        # permite lanzar manualmente

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install
        working-directory: ./scripts

      - name: Ejecutar script
        run: node generar-json.js
        working-directory: ./scripts
        env:
          TOKEN: ${{ secrets.TOKEN }}
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.REPO }}
