name: Actualizar Horarios

on:
  schedule:
    - cron: "*/1 * * * *" # cada minuto
  workflow_dispatch: # permite ejecutarlo manualmente

jobs:
  generar-json:
    runs-on: ubuntu-latest
    steps:
      - name: Chequear repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install node-fetch@

      - name: Ejecutar script para generar horarios.json
        run: node scripts/generar-json.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: Hacer commit y push del JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add horarios.json
          git commit -m "Actualizar horarios autom√°ticamente"
          git push
